///get all proudcts list
export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";

///get single proudcts details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

/// Adding new review
export const ADD_NEW_REVIEW_REQUEST = "ADD_NEW_REVIEW_REQUEST";
export const ADD_NEW_REVIEW_SUCCESS = "ADD_NEW_REVIEW_SUCCESS";
export const ADD_NEW_REVIEW_FAIL = "ADD_NEW_REVIEW_FAIL";
