///get all USERs list for admin
export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST";
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS";
export const ADMIN_ALL_USERS_FAIL = "ADMIN_ALL_USERS_FAIL";

///get USER details at admin side
export const ADMIN_USER_DETAILS_REQUEST = "ADMIN_USER_DETAILS_REQUEST";
export const ADMIN_USER_DETAILS_SUCCESS = "ADMIN_USER_DETAILS_SUCCESS";
export const ADMIN_USER_DETAILS_FAIL = "ADMIN_USER_DETAILS_FAIL";

///Delete USER at admin side
export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL";

///Update USER at admin side
export const ADMIN_USER_UPDATE_REQUEST = "ADMIN_USER_UPDATE_REQUEST";
export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS";
export const ADMIN_USER_UPDATE_FAIL = "ADMIN_USER_UPDATE_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
