///get all REVIEWS list for admin
export const ADMIN_ALL_REVIEWS_REQUEST = "ADMIN_ALL_REVIEWS_REQUEST";
export const ADMIN_ALL_REVIEWS_SUCCESS = "ADMIN_ALL_REVIEWS_SUCCESS";
export const ADMIN_ALL_REVIEWS_FAIL = "ADMIN_ALL_REVIEWS_FAIL";

///Delete REVIEW at admin side
export const ADMIN_REVIEW_DELETE_REQUEST = "ADMIN_REVIEW_DELETE_REQUEST";
export const ADMIN_REVIEW_DELETE_SUCCESS = "ADMIN_REVIEW_DELETE_SUCCESS";
export const ADMIN_REVIEW_DELETE_FAIL = "ADMIN_REVIEW_DELETE_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
