///get all orders list for admin
export const ADMIN_ALL_ORDERS_REQUEST = "ADMIN_ALL_ORDERS_REQUEST";
export const ADMIN_ALL_ORDERS_SUCCESS = "ADMIN_ALL_ORDERS_SUCCESS";
export const ADMIN_ALL_ORDERS_FAIL = "ADMIN_ALL_ORDERS_FAIL";

///get order details at admin side
export const ADMIN_ORDER_DETAILS_REQUEST = "ADMIN_ORDER_DETAILS_REQUEST";
export const ADMIN_ORDER_DETAILS_SUCCESS = "ADMIN_ORDER_DETAILS_SUCCESS";
export const ADMIN_ORDER_DETAILS_FAIL = "ADMIN_ORDER_DETAILS_FAIL";

///Delete order at admin side
export const ADMIN_ORDER_DELETE_REQUEST = "ADMIN_ORDER_DELETE_REQUEST";
export const ADMIN_ORDER_DELETE_SUCCESS = "ADMIN_ORDER_DELETE_SUCCESS";
export const ADMIN_ORDER_DELETE_FAIL = "ADMIN_ORDER_DELETE_FAIL";

///Update order at admin side
export const ADMIN_ORDER_UPDATE_REQUEST = "ADMIN_ORDER_UPDATE_REQUEST";
export const ADMIN_ORDER_UPDATE_SUCCESS = "ADMIN_ORDER_UPDATE_SUCCESS";
export const ADMIN_ORDER_UPDATE_FAIL = "ADMIN_ORDER_UPDATE_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
