///get all proudcts list for admin
export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";

///create a new proudct at admin side
export const ADMIN_PRODUCT_CREATE_REQUEST = "ADMIN_PRODUCT_CREATE_REQUEST";
export const ADMIN_PRODUCT_CREATE_SUCCESS = "ADMIN_PRODUCT_CREATE_SUCCESS";
export const ADMIN_PRODUCT_CREATE_FAIL = "ADMIN_PRODUCT_CREATE_FAIL";

///Delete proudct at admin side
export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST";
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL";

///Update proudct at admin side
export const ADMIN_PRODUCT_UPDATE_REQUEST = "ADMIN_PRODUCT_UPDATE_REQUEST";
export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAIL = "ADMIN_PRODUCT_UPDATE_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
